export { scanProject } from "./scanner";
export { resolveConfig } from "./config";
export type { CliFlags } from "./config";
export { compressAdvisories, analyzeSourceUsage } from "./analysis";
export type { CompressedAdvisory, CompressionResult, CompressionStats, SourceFileInfo, SourceAnalysisResult } from "./analysis";
export { runAudit } from "./agent";
export type { AgentStep, AuditReport } from "./agent";
export { formatOutput } from "./output";
export type { OutputFormat } from "./output";
export { createLlmClient } from "./llm";
export type { LlmClient, LlmClientResponse } from "./llm";
export type { ParsedProject, Dependency } from "./types/dependency";
export type { Advisory, Severity } from "./types/advisory";
export type { AnalysisResult, Report, RiskLevel, UsageStatus } from "./types/report";
export type { LlmProvider, LlmConfig, AuditConfig, AppConfig, AuditMode } from "./types/config";
export { DependencyCache } from "./cache";
export type { CacheStats } from "./cache";
export { AuditError, ScannerError, ConfigError, NetworkError, LlmError } from "./utils/errors";
